// Every on-screen string, per language (replaces the old teks-id.json).
import { LANG } from './fmt';
import kontak from '../../kontak.json';

const ID = {
  words: ['Dirancang.', 'Dibangun.', 'Diluncurkan.'],
  chLead: 'Website custom untuk',
  chWords: ['bisnis.', 'portofolio.', 'skripsi.'],
  revenue: 'Omzet minggu ini',
  days: ['Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'],
  rev: (v: number) => `Rp ${v.toFixed(1).replace('.', ',')} jt`,
  toast: 'Ditambahkan ke keranjang',
  addCart: 'Tambah ke keranjang',
  orderWa: 'Pesan via WhatsApp',
  priceLabel: 'Harga per lusin',
  category: 'Kategori:',
  categoryVal: 'Produk Bayi',
  thesis: 'Progres skripsi',
  complete: (p: number) => `${p}% selesai`,
  chapters: ['Pendahuluan', 'Tinjauan pustaka', 'Metodologi penelitian', 'Hasil dan pembahasan', 'Kesimpulan dan saran'],
  diagT: 'Tingkat keyakinan',
  diagN: ['Acne vulgaris,', 'ringan'],
  nexLinks: ['Karya', 'Layanan', 'Tentang'],
  nexContact: 'Kontak',
  nexH1: ['Tampil rapi.', 'Tumbuh cepat.'],
  nexP: 'Website dan aplikasi web untuk bisnis yang peduli detail, dari sketsa pertama sampai hari peluncuran.',
  nexB1: 'Mulai sekarang',
  nexB2: 'Lihat karya',
  nexF: [['Aman sejak awal', 'Login dan data terlindungi sejak hari pertama.'], ['Siap berkembang', 'Tambah halaman dan fitur seiring bisnis Anda tumbuh.'], ['Dukungan sepenuh hati', 'Tim sungguhan yang tetap sigap setelah rilis.']],
  cap6: ['Sempurna di', 'setiap layar.'],
  stats: ['proyek selesai', 'klien puas'],
  kv: ['Konsultasi gratis.', 'Harga transparan.'],
  cta: 'Siap bangun website Anda?',
  sub: 'Konsultasi gratis sebelum Anda memutuskan.',
  qr: ['Scan untuk', 'konsultasi via WA'],
  qrFile: 'assets/qr-wa-id.svg',
};

const EN: typeof ID = {
  words: ['Designed.', 'Built.', 'Launched.'],
  chLead: 'Custom web solutions for',
  chWords: ['businesses.', 'portfolios.', 'academic systems.'],
  revenue: 'Revenue this week',
  days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  rev: (v: number) => `Rp ${v.toFixed(1)}M`,
  toast: 'Added to cart',
  addCart: 'Add to cart',
  orderWa: 'Order via WhatsApp',
  priceLabel: 'Price per dozen',
  category: 'Category:',
  categoryVal: 'Baby products',
  thesis: 'Thesis system',
  complete: (p: number) => `${p}% complete`,
  chapters: ['Introduction', 'Literature review', 'Methodology', 'Results and discussion', 'Conclusion'],
  diagT: 'Diagnosis confidence',
  diagN: ['Acne vulgaris,', 'mild'],
  nexLinks: ['Work', 'Services', 'About'],
  nexContact: 'Contact',
  nexH1: ['Build better.', 'Ship faster.'],
  nexP: 'Websites and web apps for teams that care about every detail, from the first sketch to launch day.',
  nexB1: 'Get started',
  nexB2: 'See our work',
  nexF: [['Secure by default', 'Protected logins and data, set up from day one.'], ['Built to grow', 'Add pages and features as your business expands.'], ['People-first support', 'Real humans who answer after launch.']],
  cap6: ['Designed for', 'every screen.'],
  stats: ['projects delivered', 'clients satisfied'],
  kv: ['Free consultation.', 'Transparent pricing.'],
  cta: 'Let’s build yours.',
  sub: 'Free consultation before you commit.',
  qr: ['Scan to chat', 'on WhatsApp'],
  qrFile: 'assets/qr-wa-en.svg',
};

export const TX = LANG === 'en' ? EN : ID;
export const WA = { tampil: kontak.tampil as string, nomor: kontak.nomor as string };
export const URL_TEXT = 'beyondstudio.site';
